from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build LaTeX-ready paper assets from canonical JSON artifacts.")
    p.add_argument("--canonical-report", type=str, default="outputs/external_performance_report.json")
    p.add_argument("--balanced-report", type=str, default="outputs/external_performance_report_policy_replay_balanced_v2.json")
    p.add_argument("--aggressive-report", type=str, default="outputs/external_performance_report_policy_replay_aggressive_v1.json")
    p.add_argument("--baseline-json", type=str, default="outputs/baseline_comparison.json")
    p.add_argument("--readiness-json", type=str, default="outputs/publication_full_rtx4050/stats_conference_readiness.json")
    p.add_argument("--fig-src", type=str, default="outputs/publication_full_rtx4050/paper_release/figures")
    p.add_argument("--paper-dir", type=str, default="paper")
    return p.parse_args()


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt(v: Any, nd: int = 3) -> str:
    try:
        return f"{float(v):.{nd}f}"
    except Exception:
        return "n/a"


def _escape_tex(s: str) -> str:
    out = s.replace("\\", "\\textbackslash{}")
    for a, b in (
        ("_", "\\_"),
        ("%", "\\%"),
        ("&", "\\&"),
        ("#", "\\#"),
        ("{", "\\{"),
        ("}", "\\}"),
    ):
        out = out.replace(a, b)
    return out


def _dataset_rows(report: dict[str, Any]) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for row in list(report.get("datasets", [])):
        key = str(row.get("dataset", "")).strip().lower()
        out[key] = row
    return out


def _write_values_tex(path: Path, readiness: dict[str, Any], canonical: dict[str, Any]) -> None:
    snap = {
        "score": readiness.get("score_10", 0.0),
        "score_cons": readiness.get("score_10_conservative", 0.0),
    }
    ok_rows = [r for r in list(canonical.get("datasets", [])) if str(r.get("status", "")).lower() == "ok"]
    lines = [
        "% Auto-generated by scripts/build_submission_paper_assets.py",
        f"\\newcommand{{\\ReadinessScore}}{{{_fmt(snap['score'], 1)}}}",
        f"\\newcommand{{\\ReadinessConservativeScore}}{{{_fmt(snap['score_cons'], 1)}}}",
        f"\\newcommand{{\\ExternalDatasetsOk}}{{{len(ok_rows)}}}",
        f"\\newcommand{{\\ExternalDatasetsTotal}}{{{len(list(canonical.get('datasets', [])))}}}",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _build_external_table(canonical: dict[str, Any]) -> list[str]:
    lines = [
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Canonical external results (FD001 policy v8).}",
        "\\label{tab:external-canonical}",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        "Dataset & RMSE & MAE & RMSE$_{last}$ & MAE$_{last}$ & RUL cov. & Tau viol.\\\\",
        "\\midrule",
    ]
    for row in list(canonical.get("datasets", [])):
        if str(row.get("status", "")).lower() != "ok":
            continue
        m = row.get("metrics", {})
        lines.append(
            f"{_escape_tex(str(row.get('dataset', 'unknown')))} & {_fmt(m.get('rmse'))} & {_fmt(m.get('mae'))} & "
            f"{_fmt(m.get('rmse_last'))} & {_fmt(m.get('mae_last'))} & {_fmt(m.get('rul_cov'))} & {_fmt(m.get('tau_v'))}\\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return lines


def _build_policy_table(canonical: dict[str, Any], balanced: dict[str, Any], aggressive: dict[str, Any]) -> list[str]:
    can_rows = _dataset_rows(canonical)
    bal_rows = _dataset_rows(balanced)
    agg_rows = _dataset_rows(aggressive)
    datasets = ["femto", "xjtu_sy", "cmapss"]

    def row_for(policy: str, report: dict[str, Any], rows: dict[str, dict[str, Any]], ds: str) -> str:
        settings = report.get("settings", {})
        alpha = _fmt(settings.get("alpha"))
        lam = _fmt(settings.get("lambda_bet"))
        margin = _fmt(settings.get("pvalue_safety_margin"))
        if ds not in rows or str(rows[ds].get("status", "")).lower() != "ok":
            return f"{policy} & {_escape_tex(ds)} & {alpha} & {lam} & {margin} & n/a & n/a & n/a\\\\"
        m = rows[ds].get("metrics", {})
        return (
            f"{policy} & {_escape_tex(ds)} & {alpha} & {lam} & {margin} & "
            f"{_fmt(m.get('rul_cov'))} & {_fmt(m.get('tau_v'))} & {_fmt(m.get('rmse'))}\\\\"
        )

    lines = [
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Policy replay from fixed checkpoints/calibration bundles. RMSE is unchanged by policy replay; coverage and tau violation are policy-sensitive.}",
        "\\label{tab:policy-replay}",
        "\\begin{tabular}{llrrrrrr}",
        "\\toprule",
        "Policy & Dataset & $\\alpha$ & $\\lambda$ & margin & RUL cov. & Tau viol. & RMSE\\\\",
        "\\midrule",
    ]
    for ds in datasets:
        lines.append(row_for("Canonical", canonical, can_rows, ds))
    lines.append("\\midrule")
    for ds in datasets:
        lines.append(row_for("Balanced", balanced, bal_rows, ds))
    lines.append("\\midrule")
    for ds in datasets:
        lines.append(row_for("Aggressive", aggressive, agg_rows, ds))
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table*}",
        "",
    ]
    return lines


def _build_baseline_table(baseline: dict[str, Any]) -> list[str]:
    methods = list(baseline.get("methods", []))
    lines = [
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Comparator package summary on internal FD001--FD004 matrix.}",
        "\\label{tab:comparators}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Method & RMSE mean & RUL cov. mean & Tau viol. mean\\\\",
        "\\midrule",
    ]
    for m in methods:
        name = str(m.get("name", "unknown"))
        s = m.get("summary", {})
        lines.append(
            f"{_escape_tex(name)} & {_fmt(s.get('rmse_mean'))} & {_fmt(s.get('rul_cov_mean'))} & {_fmt(s.get('tau_v_mean'))}\\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return lines


def _build_gate_table(readiness: dict[str, Any]) -> list[str]:
    lines = [
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Readiness gate breakdown.}",
        "\\label{tab:readiness-gates}",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Gate & Score & Weight\\\\",
        "\\midrule",
    ]
    for g in list(readiness.get("gates", [])):
        lines.append(
            f"{_escape_tex(str(g.get('name', '')))} & {_fmt(g.get('score'), 2)} & {_fmt(g.get('weight'), 2)}\\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}", ""]
    return lines


def _copy_figures(fig_src: Path, fig_dst: Path) -> list[str]:
    wanted = [
        "external_metrics_overview.png",
        "readiness_gates.png",
        "topology_vs_rul_bins.png",
        "surface_h1_vs_rul_coverage.png",
        "gamma_vs_pred_mae.png",
    ]
    fig_dst.mkdir(parents=True, exist_ok=True)
    copied: list[str] = []
    for name in wanted:
        src = fig_src / name
        if src.exists():
            shutil.copy2(src, fig_dst / name)
            copied.append(name)
    return copied


def main() -> None:
    args = parse_args()
    paper_dir = Path(args.paper_dir).resolve()
    generated = paper_dir / "generated"
    figures = paper_dir / "figures"

    canonical = _load_json(Path(args.canonical_report).resolve())
    balanced = _load_json(Path(args.balanced_report).resolve()) if Path(args.balanced_report).exists() else {"datasets": [], "settings": {}}
    aggressive = _load_json(Path(args.aggressive_report).resolve()) if Path(args.aggressive_report).exists() else {"datasets": [], "settings": {}}
    baseline = _load_json(Path(args.baseline_json).resolve())
    readiness = _load_json(Path(args.readiness_json).resolve())

    tables: list[str] = []
    tables.extend(_build_external_table(canonical))
    tables.extend(_build_policy_table(canonical, balanced, aggressive))
    tables.extend(_build_baseline_table(baseline))
    tables.extend(_build_gate_table(readiness))

    generated.mkdir(parents=True, exist_ok=True)
    (generated / "tables.tex").write_text("\n".join(tables), encoding="utf-8")
    _write_values_tex(generated / "values.tex", readiness=readiness, canonical=canonical)

    copied = _copy_figures(Path(args.fig_src).resolve(), figures)
    provenance = {
        "canonical_report": str(Path(args.canonical_report).resolve()),
        "balanced_report": str(Path(args.balanced_report).resolve()),
        "aggressive_report": str(Path(args.aggressive_report).resolve()),
        "baseline_json": str(Path(args.baseline_json).resolve()),
        "readiness_json": str(Path(args.readiness_json).resolve()),
        "figures_copied": copied,
    }
    (generated / "provenance.json").write_text(json.dumps(provenance, indent=2, allow_nan=False), encoding="utf-8")

    print(f"Wrote: {generated / 'tables.tex'}")
    print(f"Wrote: {generated / 'values.tex'}")
    print(f"Wrote: {generated / 'provenance.json'}")
    print(f"Copied figures: {len(copied)}")


if __name__ == "__main__":
    main()

